# Site settings
title: Jeremy's Website
description: A website compiling some personal projects and some other things.
theme: just-the-docs
url: https://Awayfaring.github.io
baseurl: ""

# Repository information
repository: Awayfaring/Awayfaring.github.io

# Auxiliary navigation links
aux_links:
  Template Repository: https://github.com/Awayfaring/Awayfaring.github.io

# Makes aux links open in a new tab
aux_links_new_tab: false

#
color_scheme: dark

# Plugins
plugins:
  - jekyll-katex
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

# KaTeX configuration
katex:
  use_cdn: true
  rendering_options:
    throw_on_error: false
    error_color: "#cc0000"

# Markdown processing
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Permalink structure
permalink: pretty

# Default layouts and settings
defaults:
  - scope:
      path: "docs"  # Content in docs folder
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""  # All other files
      type: "pages"
    values:
      layout: "default"

# Include additional directories/files
include:
  - docs
  - assets

# Exclude files/folders from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - "*.gemspec"
  - "*.gem"
  - LICENSE
  - README.md
  - .github/
  - .gitignore

# Search configuration
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Navigation
nav_enabled: true
nav_sort: case_sensitive

# Enable copy button on code blocks
enable_copy_code_button: true

# Heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer configuration
footer_content: 'Copyright &copy; 2024 Jeremy Ma. Built with Jekyll and Just the Docs theme.'

# Last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# GitHub edit links
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Awayfaring/Awayfaring.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Color scheme (nil/light, dark, or custom)
color_scheme: nil

# Liquid configuration
liquid:
  error_mode: strict
  strict_filters: true

# Compress HTML output
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Warning Box
callouts_level: quiet # or loud
callouts:
  important:
    title: Important
    color: green
  
  obs:
    title: Observation
    color: blue
    opacity: 0.75
