title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://Awayfaring.github.io

aux_links:
  Template Repository: https://github.com/Awayfaring/Awayfaring.github.io

# KaTeX configuration
katex:
  css: true
  js: true
  mhchem: true
  copy_tex: true

plugins:
  - jekyll-katex
