title: Jeremy Ma's Website
description: A website compiling some personal projects and some other things.
theme: just-the-docs
url: https://Awayfaring.github.io
aux_links:
  Template Repository: https://github.com/Awayfaring/Awayfaring.github.io

plugins:
  - jekyll-katex
  - jekyll-relative-links
# KaTeX configuration
katex:
  use_cdn: true
  rendering_options:
    throw_on_error: false
    error_color: "#cc0000"
  